### ISSUE TITLE
Prevent Spell Check

### ISSUE THREAD

**Issue by gonsie** [yyyc514/Tint#3]
Tint is great, I am just looking for a way to prevent spell check from running on the text.

The easiest fix would be to prevent the re-loading of the Plain text syntax every time a command is run (tint.py:55). This would allow me to create my own "terminal syntax" that is not spell checked.

A slightly more difficult way would be to create and include this "terminal syntax" with Tint.

Thanks!

**Comment by joshgoebel** [comment]
Oh, that's not necessary... it's just to pop it out of Markdown mode... so you could probably check `view.settings().get('syntax')` and only change it if it's still stuck in the "initial" mode.  Or have an "intro" flag and the first time you run a command it changes syntax plus nixes the flag.

If it didn't re-load how would you use your own custom syntax with it?

**Comment by gonsie** [comment]
I would create my own custom syntax, then, after typing the first command, change the syntax for the file to the custom one. Currently, every time a command is run, the syntax gets reset. Your suggestion of only setting to plain-text once after the initial command is entered would fix it.

**Comment by joshgoebel** [comment]
Resolved via e2838bd.
