### ISSUE TITLE
Feature request: color terminal

### ISSUE THREAD

**Issue by atk** [yyyc514/Tint#5]
Thank you for this awesome plugin! it would be really great to have a normal color terminal, though.

**Comment by joshgoebel** [comment]
I'm thinking this is literally impossible.  If it was it would likely require parsing of ANSI codes and a custom syntax that relied on hidden character patterns in the buffer to apply the colors (not sure if that is possible).

If someone had a patch I'd be more than happy to review it, but not something I plan on adding myself.

**Comment by atk** [comment]
Thanks for your answer.
